//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CANSnatcher
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int C_Id { get; set; }
        public int Contact__Id { get; set; }
        public Nullable<int> ContactFor__Id { get; set; }
        public byte[] timestamp { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual UniqueID UniqueID { get; set; }
    }
}
