//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CANSnatcher
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobOrder()
        {
            this.Submissions = new HashSet<Submission>();
        }
    
        public int UniqueID__Id { get; set; }
        public byte[] timestamp { get; set; }
        public string TITLE { get; set; }
        public Nullable<decimal> RATE { get; set; }
        public System.DateTime JO_START_DATE { get; set; }
        public string JO_STATUS { get; set; }
        public string JO_DESCRIPTION { get; set; }
        public int Facility__Id { get; set; }
    
        public virtual Facility Facility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Submission> Submissions { get; set; }
        public virtual UniqueID UniqueID { get; set; }
    }
}
