//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CANSnatcher
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int C_Id { get; set; }
        public int User__Id { get; set; }
        public string SETTING1 { get; set; }
        public int SETTING_VALUE { get; set; }
        public byte[] timestamp { get; set; }
    
        public virtual AppUser AppUser { get; set; }
    }
}
